development:
  adapter: sqlite3
  pool: 5
  timeout: 500

test:
  adapter: postgresql
  database: laveetris_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: laveetris
  pool: 5
  timeout: 5000