development:
  database: laveris_dev
  adapter: sqlite3
  pool: 5
  timeout: 500

test:
  adapter: postgresql
  database: laveris_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: laveris
  pool: 5
  timeout: 5000
